### ISSUE TITLE
'memset not declared' in Templates.h for ESP-32

### ISSUE THREAD

**Issue by JanKuceraCF** [olwal/microdollar#1]
I have problem when try to compile the examples, eg. MicroDollar_Standalone in Arduino Studio for ESP-32.
The error says:

`In file included from /home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.h:27:0,
                 from /home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.cpp:7:
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Recognizer.h: In instantiation of 'void Recognizer<T>::recognize(T*, int, int*, float*, float*, int) [with T = int]':
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.cpp:76:80:   required from here
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Recognizer.h:552:9: error: 'memset' was not declared in this scope
   memset(pRecognize, 0, nValues * sizeof(T));
         ^
In file included from /home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Recognizer.h:29:0,
                 from /home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.h:27,
                 from /home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.cpp:7:
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Templates.h: In instantiation of 'void Template<T>::allocate(int) [with T = int]':
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Templates.h:31:11:   required from 'void Template<T>::init(int) [with T = int]'
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Templates.h:97:4:   required from 'void Templates<T>::allocate(int, int) [with T = int]'
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Templates.h:86:11:   required from 'void Templates<T>::init(int, int) [with T = int]'
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Recognizer.h:140:2:   required from 'void Recognizer<T>::allocate() [with T = int]'
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Recognizer.h:128:10:   required from 'void Recognizer<T>::init(int, int) [with T = int]'
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/MicroDollar.cpp:20:47:   required from here
/home/jan/snap/arduino/current/Arduino/libraries/microdollar-master/src/Templates.h:46:9: error: 'memset' was not declared in this scope
   memset(points, 0, nValues);
         ^
exit status 1`

There is no such error when compiling for generic ESP8266 so I assume it would be a "fix" specific for ESP-32 ... unless it is some special option I did not figure out to use.

**Comment by JanKuceraCF** [comment]
Probably a silly one but all I had to do was to go into the Templates.h and add 
#include <Arduino.h> 
at the beginning. Most likely wasteful way to go about it, but it is a working workaround.

**Comment by olwal** [comment]
Thanks for the update, I am glad you found a solution/workaround!
